// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pybbkutebwmylnjkvzha.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB5YmJrdXRlYndteWxuamt2emhhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY0NTc3NTUsImV4cCI6MjA3MjAzMzc1NX0.xg9BrqnuJB3PZ9qgqaeQI7_BnZG-nJHvamejsRPRh58";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});